/* eslint-disable react/prop-types */
import { useState } from 'react'
import { Link, NavLink, Outlet, useNavigate } from 'react-router-dom'

const menu = [['Dashboard', '/admin/dashboard', '▦'], ['Users', '/admin/users', '♙'], ['Sellers', '/admin/sellers', '⌂'], ['Products', '/admin/products', '□'], ['Categories', '/admin/categories', '▤'], ['Orders', '/admin/orders', '◫'], ['Reports', '/admin/reports', '◒'], ['Settings', '/admin/settings', '⚙']]
const activeClass = ({ isActive }) => isActive ? 'admin-nav-link active' : 'admin-nav-link'

export function AdminLayout() {
  const [open, setOpen] = useState(false); const navigate = useNavigate(); const user = JSON.parse(localStorage.getItem('thread_user') || 'null'); const signOut = () => { localStorage.removeItem('thread_token'); localStorage.removeItem('thread_user'); navigate('/login') }
  return <div className="admin-workspace"><aside className={open ? 'admin-sidebar mobile-open' : 'admin-sidebar'}><Link className="admin-brand" to="/admin/dashboard" onClick={() => setOpen(false)}>thread<span>.</span><small>ADMIN</small></Link><nav className="admin-sidebar-nav">{menu.map(([label, path, icon]) => <NavLink className={activeClass} to={path} key={path} onClick={() => setOpen(false)}><i>{icon}</i>{label}</NavLink>)}</nav><button className="admin-logout" onClick={signOut}><i>↪</i> Logout</button></aside>{open && <button className="admin-sidebar-overlay" aria-label="Close navigation" onClick={() => setOpen(false)} />}<div className="admin-main"><AdminNavbar user={user} onMenu={() => setOpen(!open)} /><Outlet /></div></div>
}

function AdminNavbar({ user, onMenu }) { const navigate = useNavigate(); const [search, setSearch] = useState(''); return <header className="admin-navbar"><button className="admin-menu-button" onClick={onMenu} aria-label="Open admin navigation">☰</button><div className="admin-search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && navigate(`/admin/products?search=${encodeURIComponent(search)}`)} placeholder="Search users, products, orders..." /></div><div className="admin-navbar-actions"><button className="admin-notification" aria-label="Notifications">♧<b>3</b></button><span className="admin-divider" /><button className="admin-profile" onClick={() => navigate('/admin/settings')}><span>{user?.name?.slice(0, 2).toUpperCase() || 'AD'}</span><strong>{user?.name || 'Administrator'}</strong><small>Admin</small></button></div></header> }
export function AdminPage({ eyebrow, title, description, action, children }) { return <main className="admin-page"><div className="admin-page-heading"><div><p className="admin-eyebrow">{eyebrow}</p><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div>{children}</main> }
export function StatsCard({ label, value, detail, tone = 'orange' }) { return <article className={`admin-stat-card ${tone}`}><div className="admin-stat-icon">{tone === 'orange' ? '↗' : tone === 'green' ? '✓' : tone === 'yellow' ? '◷' : '◈'}</div><span>{label}</span><strong>{value}</strong><small>{detail}</small></article> }
export function StatusBadge({ value }) { const status = String(value || 'pending').toLowerCase(); return <span className={`admin-status ${status}`}>{status}</span> }
export function Panel({ title, action, children, className = '' }) { return <section className={`admin-panel ${className}`}><div className="admin-panel-heading"><h2>{title}</h2>{action}</div>{children}</section> }
export function SearchBar({ value, onChange, placeholder = 'Search...' }) { return <label className="admin-table-search"><span>⌕</span><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label> }
export function EmptyState({ message = 'Nothing to show yet.' }) { return <div className="admin-empty"><span>◇</span><p>{message}</p></div> }
export function LoadingSkeleton() { return <div className="admin-skeleton"><span /><span /><span /></div> }
export function ConfirmationModal({ title, message, onConfirm, onCancel }) { return <div className="admin-modal-backdrop"><div className="admin-modal"><h2>{title}</h2><p>{message}</p><div><button className="admin-button muted" onClick={onCancel}>Cancel</button><button className="admin-button danger" onClick={onConfirm}>Confirm</button></div></div></div> }
export function AdminTable({ columns, children, empty = 'No records found.' }) { return <div className="admin-table-wrap"><table className="admin-table"><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{children}</tbody></table>{!children?.length && <EmptyState message={empty} />}</div> }
