const bcrypt = require('bcryptjs')
const jwt = require('jsonwebtoken')
const { store, id, cleanUser, getUser, isMongo, models } = require('../services/store')

const token = (user) => jwt.sign({ id: String(user.id || user._id), role: user.role }, process.env.JWT_SECRET || 'thread-development-secret', { expiresIn: '7d' })
const cleanDoc = (document) => { if (!document) return document; const value = document.toObject ? document.toObject() : document; const { _id, __v, ...rest } = value; return { ...rest, id: String(value.id || _id) } }
const cleanProduct = (product) => { const value = cleanDoc(product); return value ? { ...value, images: value.images?.length ? value.images : ['/cotton-energy-logo.svg'] } : value }
const auth = async (req, res) => {
  const { name, email, password, role = 'customer' } = req.body
  if (!name || !email || !password) return res.status(400).json({ message: 'Name, email, and password are required.' })
  if (password.length < 6) return res.status(400).json({ message: 'Password must be at least 6 characters.' })
  const normalized = email.toLowerCase().trim()
  if (isMongo() ? await models.User.exists({ email: normalized }) : store.users.some((user) => user.email === normalized)) return res.status(409).json({ message: 'An account with this email already exists.' })
  const safeRole = role === 'seller' ? 'seller' : 'customer'
  const user = { id: id(), name: name.trim(), email: normalized, password: await bcrypt.hash(password, 10), role: safeRole, status: safeRole === 'seller' ? 'pending' : 'active' }
  if (isMongo()) { const saved = await models.User.create(user); if (safeRole === 'seller') await models.Seller.create({ userId: saved._id, businessName: name.trim(), approvalStatus: 'pending' }); return res.status(201).json({ user: cleanUser(saved.toObject()), token: token(saved) }) }
  store.users.push(user)
  if (safeRole === 'seller') store.sellers.push({ id: id(), userId: user.id, businessName: name.trim(), approvalStatus: 'pending' })
  res.status(201).json({ user: cleanUser(user), token: token(user) })
}
const login = async (req, res) => {
  const user = isMongo() ? await models.User.findOne({ email: req.body.email?.toLowerCase().trim() }).lean() : store.users.find((item) => item.email === req.body.email?.toLowerCase().trim())
  if (!user || !(await bcrypt.compare(req.body.password || '', user.password))) return res.status(401).json({ message: 'Invalid email or password.' })
  if (user.status === 'pending') return res.status(403).json({ message: 'Your seller account is waiting for admin approval.' })
  res.json({ user: cleanUser(user), token: token(user) })
}
const listProducts = async (req, res) => { if (isMongo()) { const filter = req.user?.role === 'admin' ? {} : req.user?.role === 'seller' ? { sellerId: req.user.id } : { status: 'approved' }; return res.json((await models.Product.find(filter).lean()).map(cleanProduct)) } const products = store.products.filter((item) => item.status === 'approved' || req.user?.role === 'admin' || item.sellerId === req.user?.id); res.json(products.map(cleanProduct)) }
const getProduct = async (req, res) => { const product = isMongo() ? await models.Product.findById(req.params.id).lean() : store.products.find((item) => item.id === req.params.id); if (!product || (product.status !== 'approved' && req.user?.role !== 'admin' && String(product.sellerId) !== String(req.user?.id))) return res.status(404).json({ message: 'Product not found.' }); res.json(cleanProduct(product)) }
const createProduct = async (req, res) => { const { title, price, stock } = req.body; if (!title || price === undefined || Number(price) < 0 || Number(stock || 0) < 0) return res.status(400).json({ message: 'Title, valid price, and valid stock are required.' }); const images = req.body.images?.length ? req.body.images : ['/cotton-energy-logo.svg']; if (isMongo()) return res.status(201).json(cleanProduct(await models.Product.create({ ...req.body, images, sellerId: req.user.id, price: Number(price), stock: Number(stock || 0), status: 'pending' }))); const product = { id: id(), ...req.body, images, sellerId: req.user.id, price: Number(price), stock: Number(stock || 0), status: 'pending' }; store.products.push(product); res.status(201).json(product) }
const updateProduct = async (req, res) => { if (isMongo()) { const product = await models.Product.findById(req.params.id); if (!product) return res.status(404).json({ message: 'Product not found.' }); if (req.user.role !== 'admin' && String(product.sellerId) !== String(req.user.id)) return res.status(403).json({ message: 'Not your product.' }); Object.assign(product, req.body, { status: req.user.role === 'admin' ? req.body.status || product.status : 'pending' }); return res.json(await product.save()) } const product = store.products.find((item) => item.id === req.params.id); if (!product) return res.status(404).json({ message: 'Product not found.' }); if (req.user.role !== 'admin' && product.sellerId !== req.user.id) return res.status(403).json({ message: 'Not your product.' }); Object.assign(product, req.body, { status: req.user.role === 'admin' ? req.body.status || product.status : 'pending' }); res.json(product) }
const deleteProduct = async (req, res) => { if (isMongo()) { const product = await models.Product.findById(req.params.id); if (!product) return res.status(404).json({ message: 'Product not found.' }); if (req.user.role !== 'admin' && String(product.sellerId) !== String(req.user.id)) return res.status(403).json({ message: 'Not your product.' }); await models.Product.deleteOne({ _id: req.params.id }); return res.status(204).end() } const index = store.products.findIndex((item) => item.id === req.params.id); if (index < 0) return res.status(404).json({ message: 'Product not found.' }); store.products.splice(index, 1); res.status(204).end() }
const listCategories = async (req, res) => res.json(isMongo() ? (await models.Category.find().lean()).map(cleanDoc) : store.categories)
const createCategory = async (req, res) => { if (!req.body.name?.trim()) return res.status(400).json({ message: 'Category name is required.' }); if (isMongo()) return res.status(201).json(cleanDoc(await models.Category.create({ name: req.body.name.trim() }))); const category = { id: id(), name: req.body.name.trim() }; store.categories.push(category); res.status(201).json(category) }
const deleteCategory = async (req, res) => { if (isMongo()) { const result = await models.Category.deleteOne({ _id: req.params.id }); if (!result.deletedCount) return res.status(404).json({ message: 'Category not found.' }); return res.status(204).end() } const index = store.categories.findIndex((item) => item.id === req.params.id); if (index < 0) return res.status(404).json({ message: 'Category not found.' }); store.categories.splice(index, 1); res.status(204).end() }
const updateCategory = async (req, res) => { if (!req.body.name?.trim()) return res.status(400).json({ message: 'Category name is required.' }); if (isMongo()) { const category = await models.Category.findByIdAndUpdate(req.params.id, { name: req.body.name.trim() }, { new: true }); return category ? res.json(cleanDoc(category)) : res.status(404).json({ message: 'Category not found.' }) } const category = store.categories.find((item) => item.id === req.params.id); if (!category) return res.status(404).json({ message: 'Category not found.' }); category.name = req.body.name.trim(); res.json(category) }
const listUsers = async (req, res) => res.json(isMongo() ? (await models.User.find().lean()).map(cleanUser) : store.users.map(cleanUser))
const updateUser = async (req, res) => { if (req.body.status && !['active', 'pending', 'blocked'].includes(req.body.status)) return res.status(400).json({ message: 'Invalid user status.' }); if (isMongo()) { const user = await models.User.findByIdAndUpdate(req.params.id, { $set: req.body }, { new: true }).lean(); return user ? res.json(cleanUser(user)) : res.status(404).json({ message: 'User not found.' }) } const user = getUser(req.params.id); if (!user) return res.status(404).json({ message: 'User not found.' }); Object.assign(user, { name: req.body.name || user.name, phone: req.body.phone ?? user.phone, address: req.body.address ?? user.address, status: req.body.status || user.status }); res.json(cleanUser(user)) }
const deleteUser = async (req, res) => { if (isMongo()) { const user = await models.User.findById(req.params.id); if (!user) return res.status(404).json({ message: 'User not found.' }); if (user.role === 'admin') return res.status(400).json({ message: 'Admin accounts cannot be deleted.' }); await models.User.deleteOne({ _id: req.params.id }); await models.Seller.deleteMany({ userId: req.params.id }); return res.status(204).end() } const index = store.users.findIndex((user) => user.id === req.params.id); if (index < 0) return res.status(404).json({ message: 'User not found.' }); if (store.users[index].role === 'admin') return res.status(400).json({ message: 'Admin accounts cannot be deleted.' }); store.users.splice(index, 1); store.sellers = store.sellers.filter((seller) => seller.userId !== req.params.id); res.status(204).end() }
const approveSeller = async (req, res) => { const nextStatus = req.body.approvalStatus === 'rejected' ? 'blocked' : req.body.approvalStatus === 'approved' ? 'active' : null; if (!nextStatus) return res.status(400).json({ message: 'Approval status must be approved or rejected.' }); if (isMongo()) { const user = await models.User.findOneAndUpdate({ _id: req.params.id, role: 'seller' }, { status: nextStatus }, { new: true }).lean(); if (!user) return res.status(404).json({ message: 'Seller not found.' }); await models.Seller.findOneAndUpdate({ userId: req.params.id }, { approvalStatus: req.body.approvalStatus }, { upsert: true }); return res.json(cleanUser(user)) } const user = getUser(req.params.id); if (!user) return res.status(404).json({ message: 'User not found.' }); user.status = nextStatus; const seller = store.sellers.find((item) => item.userId === user.id); if (seller) seller.approvalStatus = req.body.approvalStatus; res.json(cleanUser(user)) }
const getCart = async (req, res) => res.json(isMongo() ? cleanDoc(await models.Cart.findOne({ customerId: req.user.id }).lean() || { customerId: req.user.id, items: [] }) : store.carts.find((item) => item.customerId === req.user.id) || { customerId: req.user.id, items: [] })
const saveCart = async (req, res) => { if (!Array.isArray(req.body.items)) return res.status(400).json({ message: 'Cart items must be an array.' }); if (isMongo()) return res.json(cleanDoc(await models.Cart.findOneAndUpdate({ customerId: req.user.id }, { customerId: req.user.id, items: req.body.items }, { new: true, upsert: true }))); let cart = store.carts.find((item) => item.customerId === req.user.id); if (!cart) { cart = { id: id(), customerId: req.user.id, items: [] }; store.carts.push(cart) } cart.items = req.body.items; res.json(cart) }
const toggleWishlist = (req, res) => { let wishlist = store.wishlists.find((item) => item.customerId === req.user.id); if (!wishlist) { wishlist = { id: id(), customerId: req.user.id, productIds: [] }; store.wishlists.push(wishlist) }; wishlist.productIds = wishlist.productIds.includes(req.params.productId) ? wishlist.productIds.filter((productId) => productId !== req.params.productId) : [...wishlist.productIds, req.params.productId]; res.json(wishlist) }
const getWishlist = (req, res) => { const wishlist = store.wishlists.find((item) => item.customerId === req.user.id) || { customerId: req.user.id, productIds: [] }; res.json({ ...wishlist, products: wishlist.productIds.map((productId) => store.products.find((product) => product.id === productId)).filter(Boolean) }) }
const createOrder = (req, res) => { if (!Array.isArray(req.body.items) || !req.body.items.length) return res.status(400).json({ message: 'At least one order item is required.' }); const items = req.body.items.map((item) => { const product = store.products.find((productItem) => productItem.id === item.productId); return { productId: item.productId, sellerId: product?.sellerId, title: product?.title, price: product?.price || 0, quantity: Math.max(1, Number(item.quantity || 1)) } }).filter((item) => item.title); if (!items.length) return res.status(400).json({ message: 'No valid products were found.' }); const order = { id: id(), customerId: req.user.id, items, totalAmount: items.reduce((sum, item) => sum + item.price * item.quantity, 0), shippingAddress: req.body.shippingAddress || req.user.address || '', orderStatus: 'pending', createdAt: new Date().toISOString() }; store.orders.push(order); res.status(201).json(order) }
const listOrders = (req, res) => res.json(store.orders.filter((order) => req.user.role === 'admin' || order.customerId === req.user.id || order.items.some((item) => item.sellerId === req.user.id)))
const updateOrder = (req, res) => { const allowed = ['pending', 'confirmed', 'shipped', 'delivered', 'cancelled']; if (!allowed.includes(req.body.orderStatus)) return res.status(400).json({ message: 'Invalid order status.' }); const order = store.orders.find((item) => item.id === req.params.id); if (!order) return res.status(404).json({ message: 'Order not found.' }); if (req.user.role !== 'admin' && !order.items.some((item) => item.sellerId === req.user.id)) return res.status(403).json({ message: 'Not your order.' }); order.orderStatus = req.body.orderStatus; res.json(order) }
const listReviews = (req, res) => res.json(store.reviews.filter((item) => item.productId === req.params.productId))
const createReview = (req, res) => { const review = { id: id(), customerId: req.user.id, productId: req.params.productId, rating: Number(req.body.rating), comment: req.body.comment || '' }; store.reviews.push(review); res.status(201).json(review) }
const profile = async (req, res) => { if (!req.body.name?.trim()) return res.status(400).json({ message: 'Name is required.' }); if (isMongo()) { const user = await models.User.findByIdAndUpdate(req.user.id, { name: req.body.name.trim(), phone: req.body.phone, address: req.body.address }, { new: true }).lean(); return user ? res.json(cleanUser(user)) : res.status(404).json({ message: 'User not found.' }) } const user = getUser(req.user.id); if (!user) return res.status(404).json({ message: 'User not found.' }); Object.assign(user, { name: req.body.name.trim(), phone: req.body.phone, address: req.body.address }); res.json(cleanUser(user)) }
const dashboard = (req, res) => res.json({ users: store.users.length, products: store.products.length, pendingProducts: store.products.filter((item) => item.status === 'pending').length, pendingSellers: store.sellers.filter((item) => item.approvalStatus === 'pending').length, orders: store.orders.length })
module.exports = { auth, login, listProducts, getProduct, createProduct, updateProduct, deleteProduct, listCategories, createCategory, deleteCategory, updateCategory, listUsers, updateUser, deleteUser, approveSeller, getCart, saveCart, getWishlist, toggleWishlist, createOrder, listOrders, updateOrder, listReviews, createReview, profile, dashboard }
