const express = require('express')
const controller = require('../controllers/apiController')
const { authenticate, optionalAuthenticate, authorize } = require('../middleware/auth')
const router = express.Router()

router.post('/auth/register', controller.auth)
router.post('/auth/login', controller.login)
router.get('/products', optionalAuthenticate, controller.listProducts)
router.get('/products/:id', controller.getProduct)
router.get('/categories', controller.listCategories)
router.get('/products/:productId/reviews', controller.listReviews)
router.post('/products/:productId/reviews', authenticate, authorize('customer'), controller.createReview)
router.get('/products', controller.listProducts)
router.post('/products', authenticate, authorize('seller', 'admin'), controller.createProduct)
router.patch('/products/:id', authenticate, authorize('seller', 'admin'), controller.updateProduct)
router.delete('/products/:id', authenticate, authorize('seller', 'admin'), controller.deleteProduct)
router.post('/categories', authenticate, authorize('admin'), controller.createCategory)
router.delete('/categories/:id', authenticate, authorize('admin'), controller.deleteCategory)
router.patch('/categories/:id', authenticate, authorize('admin'), controller.updateCategory)
router.get('/cart', authenticate, authorize('customer'), controller.getCart)
router.put('/cart', authenticate, authorize('customer'), controller.saveCart)
router.get('/wishlist', authenticate, authorize('customer'), controller.getWishlist)
router.post('/wishlist/:productId', authenticate, authorize('customer'), controller.toggleWishlist)
router.post('/orders', authenticate, authorize('customer'), controller.createOrder)
router.get('/orders', authenticate, controller.listOrders)
router.patch('/orders/:id', authenticate, authorize('seller', 'admin'), controller.updateOrder)
router.get('/admin/users', authenticate, authorize('admin'), controller.listUsers)
router.patch('/admin/users/:id', authenticate, authorize('admin'), controller.updateUser)
router.delete('/admin/users/:id', authenticate, authorize('admin'), controller.deleteUser)
router.patch('/admin/sellers/:id', authenticate, authorize('admin'), controller.approveSeller)
router.patch('/admin/products/:id', authenticate, authorize('admin'), controller.updateProduct)
router.get('/dashboard', authenticate, controller.dashboard)
router.patch('/profile', authenticate, controller.profile)
module.exports = router
